# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://usteinfo.github.io
date_format: "ordinal"
title: 码农感悟
subtitle: "公众号：码农感悟"
description: "zhoubin的个人博客，公众号：码农感悟"
keywords: 码农感悟
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 2023
# 源码仓库，请替换成自己的
repository: usteinfo/usteinfo.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2023-09-02
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: 码农感悟
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
    # 图片灯箱效果功能
    fancybox:
        enabled: false
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: zhoubin
organization: 
organization_url: 
github_username: usteinfo
location: ChenDu, China
email: cdzhoubin@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档
    mobile-hidden: true

  -
    href: /open-source/
    label: 开源
    mobile-hidden: true

  -
    href: /fragments/
    label: 片段

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接
    mobile-hidden: true

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# disqus 配置参考：https://disqus.com
disqus:
    username: 
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/
gitment:
    owner: usteinfo
    repo: blog-comments
    oauth:
        client_id: 62c71f91549f14fcc66a
        client_secret: 1d07e46985f62433d46a0efd76a14da045d8202e
# gitalk 配置参考：https://github.com/gitalk/gitalk#install
gitalk:
    owner: usteinfo
    repo: blog-comments
    clientID: 62c71f91549f14fcc66a
    clientSecret: 1d07e46985f62433d46a0efd76a14da045d8202e
# utterances 配置参考：https://utteranc.es/
utterances:
    repo: usteinfo/blog-comments
# beaudar 配置参考：https://beaudar.lipk.org/
beaudar:
    repo: usteinfo/blog-comments
# giscus 配置参考：https://giscus.app/zh-CN
giscus:
    repo: usteinfo/blog-comments
    repo-id: R_kgDOKL8L_A
    category: Announcements
    category-id: DIC_kwDOKL8L_M4CY4xg
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: true
        footer: true
        sidebar: true
        sidebar-detail: true
        content_header: true
        content_footer: true
